# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

surv_est <- function(times, probs, newtimes) {
    .Call('_obliqueRSF_surv_est', PACKAGE = 'obliqueRSF', times, probs, newtimes)
}

innerprod <- function(x, y) {
    .Call('_obliqueRSF_innerprod', PACKAGE = 'obliqueRSF', x, y)
}

moving_average <- function(a) {
    .Call('_obliqueRSF_moving_average', PACKAGE = 'obliqueRSF', a)
}

colmeans <- function(input_mat) {
    .Call('_obliqueRSF_colmeans', PACKAGE = 'obliqueRSF', input_mat)
}

pick_node <- function(wt, cut_pnt, options) {
    .Call('_obliqueRSF_pick_node', PACKAGE = 'obliqueRSF', wt, cut_pnt, options)
}

predict_orsf <- function(forest, newx, times) {
    .Call('_obliqueRSF_predict_orsf', PACKAGE = 'obliqueRSF', forest, newx, times)
}

predict_ost <- function(ostree, newx, times) {
    .Call('_obliqueRSF_predict_ost', PACKAGE = 'obliqueRSF', ostree, newx, times)
}

seql <- function(from, to, length_out) {
    .Call('_obliqueRSF_seql', PACKAGE = 'obliqueRSF', from, to, length_out)
}

leaf_nodes <- function(nodes) {
    .Call('_obliqueRSF_leaf_nodes', PACKAGE = 'obliqueRSF', nodes)
}

unique_len_fast <- function(x) {
    .Call('_obliqueRSF_unique_len_fast', PACKAGE = 'obliqueRSF', x)
}

filter_unique <- function(v, i) {
    .Call('_obliqueRSF_filter_unique', PACKAGE = 'obliqueRSF', v, i)
}

modify_string <- function(x, newchar, newindx) {
    .Call('_obliqueRSF_modify_string', PACKAGE = 'obliqueRSF', x, newchar, newindx)
}

namegen <- function(origin_name, rhs) {
    .Call('_obliqueRSF_namegen', PACKAGE = 'obliqueRSF', origin_name, rhs)
}

find_nonconst_cols <- function(mat, indx, ncol) {
    .Call('_obliqueRSF_find_nonconst_cols', PACKAGE = 'obliqueRSF', mat, indx, ncol)
}

soft_sample <- function(x, size) {
    .Call('_obliqueRSF_soft_sample', PACKAGE = 'obliqueRSF', x, size)
}

find_indx <- function(node_ids, current_node) {
    .Call('_obliqueRSF_find_indx', PACKAGE = 'obliqueRSF', node_ids, current_node)
}

comp_preds <- function(indx, node_nobs, node_cols, bwts, dmat) {
    .Call('_obliqueRSF_comp_preds', PACKAGE = 'obliqueRSF', indx, node_nobs, node_cols, bwts, dmat)
}

srv_R <- function(time_indx, status_indx, f) {
    .Call('_obliqueRSF_srv_R', PACKAGE = 'obliqueRSF', time_indx, status_indx, f)
}

lrt_R <- function(tmp_time, tmp_grp, tmp_status, f) {
    .Call('_obliqueRSF_lrt_R', PACKAGE = 'obliqueRSF', tmp_time, tmp_grp, tmp_status, f)
}

boot_R <- function(dmat, time, status, inb, f) {
    .Call('_obliqueRSF_boot_R', PACKAGE = 'obliqueRSF', dmat, time, status, inb, f)
}

eval_forest_R <- function(oob_predictions, time, status, eval_times, f) {
    .Call('_obliqueRSF_eval_forest_R', PACKAGE = 'obliqueRSF', oob_predictions, time, status, eval_times, f)
}

net_R <- function(dmat, time, status, indx, cols, mtry, alpha, f) {
    .Call('_obliqueRSF_net_R', PACKAGE = 'obliqueRSF', dmat, time, status, indx, cols, mtry, alpha, f)
}

tune_node <- function(dmat, bwts_mat, indx, node_cols, status_indx, time_indx, node, node_nobs, min_obs_in_leaf_node, min_events_in_leaf_node, nsplit, mincriterion, split_eval_Rfun) {
    .Call('_obliqueRSF_tune_node', PACKAGE = 'obliqueRSF', dmat, bwts_mat, indx, node_cols, status_indx, time_indx, node, node_nobs, min_obs_in_leaf_node, min_events_in_leaf_node, nsplit, mincriterion, split_eval_Rfun)
}

OST <- function(dmat, features, alpha, time, status, inbag_orsf_ids, min_events_to_split_node, min_obs_to_split_node, min_obs_in_leaf_node, min_events_in_leaf_node, mtry, nsplit, mincriterion, split_eval_Rfun, surv_KM_Rfun, glmnet_Rfun) {
    .Call('_obliqueRSF_OST', PACKAGE = 'obliqueRSF', dmat, features, alpha, time, status, inbag_orsf_ids, min_events_to_split_node, min_obs_to_split_node, min_obs_in_leaf_node, min_events_in_leaf_node, mtry, nsplit, mincriterion, split_eval_Rfun, surv_KM_Rfun, glmnet_Rfun)
}

ORSFcpp <- function(dmat, features, alpha, time, status, min_events_to_split_node, min_obs_to_split_node, min_obs_in_leaf_node, min_events_in_leaf_node, mtry, nsplit, ntree, mincriterion, verbose, split_eval_Rfun, surv_KM_Rfun, bootstrap_Rfun, glmnet_Rfun, forest_eval_Rfun) {
    .Call('_obliqueRSF_ORSFcpp', PACKAGE = 'obliqueRSF', dmat, features, alpha, time, status, min_events_to_split_node, min_obs_to_split_node, min_obs_in_leaf_node, min_events_in_leaf_node, mtry, nsplit, ntree, mincriterion, verbose, split_eval_Rfun, surv_KM_Rfun, bootstrap_Rfun, glmnet_Rfun, forest_eval_Rfun)
}

