# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Survival estimate
#' 
#' this function is used to create survival step estimates.
#' 
#' @param times a numeric vector
#' @param probs a numeric vector
#' @param newtimes a numeric vector
#' @export
surv_est <- function(times, probs, newtimes) {
    .Call('_obliqueRSF_surv_est', PACKAGE = 'obliqueRSF', times, probs, newtimes)
}

#' inner product
#' 
#' this function computes an inner product of two vectors.
#' 
#' @param y a numeric vector
#' @param x a numeric vector
#' @export
innerprod <- function(x, y) {
    .Call('_obliqueRSF_innerprod', PACKAGE = 'obliqueRSF', x, y)
}

moving_average <- function(a) {
    .Call('_obliqueRSF_moving_average', PACKAGE = 'obliqueRSF', a)
}

#' column means
#' 
#' this function computes column means of a matrix.
#' 
#' @param input_mat a numeric matrix
#' @export
colmeans <- function(input_mat) {
    .Call('_obliqueRSF_colmeans', PACKAGE = 'obliqueRSF', input_mat)
}

#' pick a node
#' 
#' this function determines which node new observations go to
#' 
#' @param wt a numeric scalar
#' @param cut_pnt a numeric scalar
#' @param options a character vector of options
#' @export
pick_node <- function(wt, cut_pnt, options) {
    .Call('_obliqueRSF_pick_node', PACKAGE = 'obliqueRSF', wt, cut_pnt, options)
}

#' which trees
#' 
#' this function identifies out-of-bag trees.
#' 
#' @param vec a numeric vector
#' @param forest a list of oblique survival trees
#' @export
which_trees <- function(vec, forest) {
    .Call('_obliqueRSF_which_trees', PACKAGE = 'obliqueRSF', vec, forest)
}

#' Predictions from an ORSF
#' @param forest A list of oblique survival trees.
#' @param newx a data matrix.
#' @param times A vector of times in the range of the response variable, e.g. times when the response is a survival object, at which to return the survival probabilities.
#' @return A matrix of survival probabilities containing 1 row for each observation and 1 column for each value in times.
#' @export
predict_orsf <- function(forest, newx, times) {
    .Call('_obliqueRSF_predict_orsf', PACKAGE = 'obliqueRSF', forest, newx, times)
}

#' Predictions from an OST
#' @param ostree an oblique survival tree object.
#' @param newx a data matrix.
#' @param times A vector of times in the range of the response variable, e.g. times when the response is a survival object, at which to return the survival probabilities.
#' @return A matrix of survival probabilities containing 1 row for each observation and 1 column for each value in times.
#' @export
predict_ost <- function(ostree, newx, times) {
    .Call('_obliqueRSF_predict_ost', PACKAGE = 'obliqueRSF', ostree, newx, times)
}

